# Site settings
title: Som Farm
email: info@som.eu
phone: +36-30-821-4589
description: > # this means to ignore newlines until "baseurl:"
baseurl: "/som/" # the subpath of your site, e.g. /blog/
url: "https://vestalux.github.io" # the base hostname & protocol for your site

facebook_username:
github_username:

# Build settings
markdown: kramdown

collections:
  portfolio:
    output: true
    permalink: portfolio/:title/
